import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/nav";
import { Source_Code_Pro } from 'next/font/google'
import { cn } from "@/utils/cn";

const sourceCodePro = Source_Code_Pro({ subsets : ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-black", sourceCodePro.className)}>
        <main className="w-full h-full">
          <Nav />
          <div className="mt-11 h-full w-full">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
